#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["IbanApp.Api/IbanApp.Api.csproj", "IbanApp.Api/"]
RUN dotnet restore "IbanApp.Api/IbanApp.Api.csproj"
COPY . .
WORKDIR "/src/IbanApp.Api"
RUN dotnet build "IbanApp.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IbanApp.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IbanApp.Api.dll"]